def bbcLogo():
    print()
    print("====================================")
    print("====================================")
    print("  BBBBBB      BBBBBB      CCCCCCCC  ")
    print("  BB    BB    BB    BB    CCCCCCCC  ")
    print("  BB    BB    BB    BB    CC        ")
    print("  BBBBBB      BBBBBB      CC        ")
    print("  BB    BB    BB    BB    CC        ")
    print("  BB    BB    BB    BB    CCCCCCCC  ")
    print("  BBBBBB      BBBBBB      CCCCCCCC  ")
    print("====================================")
    print("====================================")
    print()
bbcLogo()

print("EastEnders is a British television soap opera,")
print("first broadcast on 19 February 1985.")
print("EastEnders storylines examine the domestic and")
print("professional lives of the people who live and work")
print("in the fictional London Borough of Walford in the East End of London.")
